### PR TITLE
FIX: Filter plotting

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by jasmainak** [comment]
Cool, thanks @Eric89GXL !

Why do we have a kink in the curve in the B subplot at 50 Hz?

**Comment by larsoner** [comment]
It's the first side-lobe of the window used to design the filter. Speaking of which, those actually changed from 0.12 (hann) and 0.16 (hamming), too, so those should be added

**Comment by jasmainak** [comment]
Ah, makes sense! yes, but the `design_filter` function doesn't seem to have that option. Now that I think of it, that's probably the reason we had to do the triaging?

**Comment by jasmainak** [comment]
Oh wait, never mind. It's in the `create_filter` ... which makes sense

**Pull request merged**
